const MALE = "Male";
const FEMALE = "Female";
const NONE = "NONE";
const PERSON_NOT_FOUND = "PERSON_NOT_FOUND";
const CHILD_ADDITION_FAILED = "CHILD_ADDITION_FAILED";
const CHILD_ADDITION_SUCCEEDED = "CHILD_ADDITION_SUCCEEDED";
const ADD_CHILD = "ADD_CHILD";
const GET_RELATIONSHIP = "GET_RELATIONSHIP";

module.exports = {
	MALE,
	FEMALE,
	NONE,
	PERSON_NOT_FOUND,
	CHILD_ADDITION_FAILED,
	CHILD_ADDITION_SUCCEEDED,
	ADD_CHILD,
	GET_RELATIONSHIP,
};
