const MALE = "Male";
const FEMALE = "Female";
const PERSON_NOT_FOUND = "PERSON_NOT_FOUND";
const CHILD_ADDITION_FAILED = "CHILD_ADDITION_FAILED";
const CHILD_ADDITION_SUCCEEDED = "CHILD_ADDITION_SUCCEEDED";

module.exports = {
	MALE,
	FEMALE,
	PERSON_NOT_FOUND,
	CHILD_ADDITION_FAILED,
	CHILD_ADDITION_SUCCEEDED,
};
